name: Build & Test Matrix

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: ubuntu-latest, prefix: sudo, name: Linux}
        - {os: macos-latest, prefix: "", name: MacOS}
    
    runs-on: ${{ matrix.config.os }}
    name: Build & Test - ${{ matrix.config.name }} 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Build
      run: ${{ matrix.config.prefix }} ./build.sh

    - name: Run Tests
      if: success()
      run: ${{ matrix.config.prefix }} ./run_tests.sh --results-dir ./_build/test-results

    - name: Publish Results
      uses: dorny/test-reporter@v1.9.1
      with:
        name: "Moxygen Tests - ${{ matrix.config.name }}"
        path: ./_build/test-results/*.xml
        reporter: java-junit

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: test-results-${{ matrix.config.os }}
        path: ./_build/test-results/*.*
        retention-days: 14