name: BUILD_TEST_MATRIX

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Build & Test
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Build
      run: ./build.sh

    - name: Run Tests
      if: success()
      run: sudo ./run_tests.sh --results-dir ./_build/test-results

    - name: Publish Results
      uses: dorny/test-reporter@v1.9.1
      with:
        name: "${{ matrix.os }} Moxygen Tests"
        path: ./_build/test-results/*.xml
        reporter: java-junit

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: test-results-${{ matrix.os }}
        path: ./_build/test-results/*.*
        retention-days: 14