# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# This builds moxygen for Linux Ubuntu

name: linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read  #  to fetch code (actions/checkout)
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Build
      run: sudo ./build.sh

    - name: Run Tests
      if: success()
      run: sudo ./run_tests.sh --results-dir ./_build/test-results/

    - name: Publish Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: ./_build/test-results/*.xml
        github_token: ${{ github.token }}
        check_name: "Moxygen Tests - Linux"
        action_fail: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: test-results
        path: ./_build/test-results/*.*
        retention-days: 14  # customize retention for artifacts
