# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# This builds moxygen for Linux Ubuntu

name: linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read  #  to fetch code (actions/checkout)
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
    - uses: actions/checkout@v4
    - name: Build moxygen
      run: sudo ./build.sh

    - name: Set current date as env variable
      run:  printf "TIMESTAMP=$(date +%Y-%m-%d-%H:%M:%S)" >> $GITHUB_ENV

    - name: Run tests
      run: sudo ./run_tests.sh --results-dir ./_build/test-results/$TIMESTAMP

    - name: Publish results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()  # Run this step even if tests fail
      with:
        files: "./_build/test-results/${{ github.env.TIMESTAMP }}/*.xml"
        check_name: "Moxygen Test Results"
        action_fail: true
